# Generated by Django 4.0 on 2021-12-21 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxii_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRootStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('failure', 'Failure'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('request_timestamp', models.DateTimeField()),
                ('total_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='apiroot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiroot',
            name='versions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.CreateModel(
            name='ApiRootStatusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('state', models.CharField(choices=[('failure', 'Failure'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('api_root_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_details', to='taxii_server.apirootstatus')),
            ],
        ),
        migrations.AddField(
            model_name='apirootstatus',
            name='api_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='taxii_server.apiroot'),
        ),
    ]
