# Generated by Django 4.0 on 2021-12-21 22:52

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxii_server', '0002_apirootstatus_alter_apiroot_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('media_types', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('api_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='taxii_server.apiroot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('api_root', 'alias'), name='unique_alias_per_api_root'),
        ),
    ]
